name: h071221056_uiflutter
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '3.3.4'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logounhas.png
    - assets/gambar6.jpg
    - assets/gambar5.jpg
    - assets/gambar1.jpg
    - assets/gambar2.jpg
    - assets/gambar3.jpg
    - assets/gambar4.jpg